import * as fs from "fs";
import * as path from "path";
import colorPalette from "../styles/palette.ts";

function generateColorPalette() {
  const previewText = [
    "// AUTO GENERATED FILE : DO NOT EDIT THIS FILE (see scripts/color)",
    ":root {",
  ];

  Object.entries(colorPalette).forEach(([key, value]) =>
    previewText.push(`--${key}: ${value};`)
  );
  previewText.push("}");

  const scssContent = previewText.join("\n");
  const outputPath = path.join(process.cwd(), "src/styles/color.scss");

  fs.writeFileSync(outputPath, scssContent, "utf8");
  console.log("color.scss 파일이 생성되었습니다:", outputPath);
}

generateColorPalette();
